language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy2.7-5.10.0"
  - "pypy3.5-5.10.0"
# Add an IPv6 config - see the corresponding Travis issue
# https://github.com/travis-ci/travis-ci/issues/8361
matrix:
  include:
   - python: "3.7"
     dist: xenial
     before_script: |
       sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
       sudo sh -c 'echo "::1		localhost" >> /etc/hosts'
branches:
  only:
    - master
install:
  - sysctl -a
  - ifconfig
  - python -V
  - python setup.py install
script:
  - ./tests/tests.py
notifications:
  email:
    on_success: never
    on_failure: change
